apiVersion: apps/v1
kind: Deployment
metadata:
  name: coarlumini-frontend
  namespace: coarlumini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coarlumini-frontend
  template:
    metadata:
      labels:
        app: coarlumini-frontend
    spec:
      containers:
        - name: vue-app
          image: gcr.io/cloudcomputingunsa/coarlumini-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          env:
            - name: BACKEND_API_URL
              value: "http://136.114.158.67"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
